#!/bin/bash
SCRIPTS="$HOME/.config/bspwm/Scripts"
#############
# Autostart #
#############

#SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

#Dunst
dunst -b &

#Scripts
~/.config/bspwm/Scripts/wallpaper_change.sh &
#~/.config/bspwm/Scripts/Borders.sh &

##############
# Appearance #
##############

#Wallpaper
nitrogen --restore &

#Polybar
~/.config/polybar/launch.sh &

#Picom
picom --backend glx -b &

#Cursor
xsetroot -cursor_name left_ptr

#Monitor
xrandr --output HDMI-0 --mode 2560x1080 --rate 75

##############
#  BSPC      #
##############

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

#Borders and gaps
bspc config border_width         0
bspc config window_gap          15
bspc config split_ratio          0.5
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
bspc config automatic_scheme	spiral

#Mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

